spring:
  application:
    name: DesignPatterns
  datasource:
    url: jdbc:postgresql://localhost:5432/llc1
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true